spring:
  application:
    name: todo-api
  datasource:
    url: "jdbc:sqlite:./db/todo"
    username: root
    password: root
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: "jdbc:sqlite:./db/todo"
    user: root
    password: root
    validate-on-migrate: true
    locations: "classpath:db/migration"