spring:
  datasource:
    url: "jdbc:sqlite:./db/todo-test"
    username: root
    password: root
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: "jdbc:sqlite:./db/todo-test"
    user: root
    password: root
    validate-on-migrate: true
    locations: "classpath:db/migration"